language: julia
os:
    - linux
julia:
    - nightly
    - 0.5
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Crispulator"); Pkg.test("Crispulator")';
