language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.4
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Crispulator.jl"); Pkg.test("Crispulator.jl")';
